language: node_js
node_js:
  - 9
script:
  - yarn run build
  - yarn run build-storybook
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build/storybook
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: $EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
